main: me.sothatsit.flyingcarpet.FlyingCarpet
author: sothatsit
name: FlyingCarpet
version: 1.3
soft-depend: [WorldGuard]
commands:
   flyingcarpet:
      aliases: [mc,magiccarpet]
      description: 'Toggle your Flying Carpet'
permissions:
   flyingcarpet.use:
      description: 'Permission to use the flying carpet'
      default: op
   flyingcarpet.tools:
      description: 'Permission to add tools to your flying carpet'
      default: op
   flyingcarpet.light:
      description: 'Permission to add a light to your flying carpet'
      default: op
   flyingcarpet.reload:
      description: 'Permission to reload the flying carpet config'
      default: op
   flyingcarpet.teleport:
      description: 'Allow players to keep their flying carpet on teleport'
      default: false
   flyingcarpet.worldguard:
      description: 'Allow admins to add blacklisted worldguard regions'
      default: false